### PR TITLE
Use separate namespace for tests

### PR DESCRIPTION
**Pull request by szepeviktor**
@loevgaard Would you merge a PR like this?

### CODE REVIEW

**Comment by loevgaard** [comment]
Not sure why that's needed?

**Comment by szepeviktor** [comment]
Using two directories for one PSR-4 namespace technically works but not perfect.
That is the small value from me. Actually I achieve long-term robust operations with hundreds of these small things.

**Comment by loevgaard** [comment]
Hi, @szepeviktor 

Okay, I see. Can you explain why it's better or provides value? :)

**Comment by szepeviktor** [comment]
No, I am an antibusinessman, more like a scientist dealing with bytes.
All I do is digging deep to find a final solution. Many of my findings are not good for business - at least not on the short-term.

In one sentence I don't have the balls to instruct Composer to load 1 namespace from 2 directories.

**Comment by szepeviktor** [comment]
I am so happy about your question!! It makes me think about these things.

**Comment by szepeviktor** [comment]
Let's agree in a <kbd>Close</kbd>!

**Comment by loevgaard** [comment]
Okay :)

**Pull request closed without merging**
